### ISSUE TITLE
Bootstrap Group Select Example

### ISSUE THREAD

**Issue by deepfriedbrain** [wenzhixin/bootstrap-group-select#2]
I'm really interested in this feature. But I cannot find any examples of how it works. The JS Fiddle example (http://jsfiddle.net/wenyi/86es7wfp/) doesn't seem to be working. 

Thanks for your great work!

**Comment by wenzhixin** [comment]
Hi @deepfriedbrain , in my case, the JS Fiddle example is working well. Can you show me your problem?

**Comment by deepfriedbrain** [comment]
Hi @wenzhixin 

I think I misunderstood what this project is about. This is for bootstrap button group select. I'm interested in grouping with your "Bootstrap Table". I got the link from the top nav bar of your "Bootstrap Table" home page and thought that this project is to add row grouping to the table. I apologize for the confusion. 

I'm really looking for grouping on the Bootstrap Table but not able to find good options for it. I'll post my question on the Bootstrap Table GitHub. Any help would be appreciated. 

Thanks.

**Comment by wenzhixin** [comment]
OK!
